<?php
/**
 * Created by PhpStorm.
 * User: cozz
 * Date: 2018/12/13
 * Time: 11:15
 */
namespace Lib\Http\AbstractInterface;

use Zor\Config;

abstract class ViewController extends Controller
{
    protected $view;

    public function onRequest(?string $action): ?bool
    {
        $this->view = new \Smarty();
        $tempPath   = $GLOBALS['conf']->getConf('TEMP_DIR');    # 临时文件目录
        $this->view->setCompileDir("{$tempPath}/templates_c/");      # 模板编译目录
        $this->view->setCacheDir("{$tempPath}/cache/");              # 模板缓存目录
        $this->view->setTemplateDir(ROOT_PATH .'/'.MODULE_DIR.'/'. '/Views/');    # 模板文件目录
        $this->view->setCaching(false);
        return parent::onRequest($action); // TODO: Change the autogenerated stub
    }

    public function afterAction(?string $actionName): void
    {
        $this->view=null;
        parent::afterAction($actionName); // TODO: Change the autogenerated stub
    }

    /**
     * 输出模板到页面
     * @param  string|null $template 模板文件
     * @throws \Exception
     * @throws \SmartyException
     */
    function fetch($template = null)
    {
        $content = $this->view->fetch($template);
        $this->response()->write($content);
        $this->view->clearAllAssign();
        $this->view->clearAllCache();
    }

    /**
     * 添加模板变量
     * @param array|string $tpl_var 变量名
     * @param mixed        $value   变量值
     * @param boolean      $nocache 不缓存变量
     */
    function assign($tpl_var, $value = null, $nocache = false)
    {
        $this->view->assign($tpl_var, $value, $nocache);
    }
}